version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: task-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-api
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/bin/sh", "entrypoint.sh"]

volumes:
  db_data:
